# Generated by Django 6.0 on 2025-12-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='playback_tail_enabled',
            field=models.BooleanField(default=False, help_text='If enabled: when schedule ends, recording stops immediately but playback continues until (schedule_end + delay_seconds). Useful to flush the delayed buffer.'),
        ),
    ]
