# Generated by Django 6.0 on 2025-12-13 15:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcoder', '0002_channel_playback_tail_enabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='channel',
            name='delay_seconds',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='hardware_preference',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='output_url',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='record_enabled',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='target_height',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='target_width',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='video_bitrate',
        ),
        migrations.AddField(
            model_name='channel',
            name='is_test_channel',
            field=models.BooleanField(db_index=True, default=False, help_text='Marks a channel as an internal test channel (created from admin tools).'),
        ),
        migrations.AddField(
            model_name='channel',
            name='output_target',
            field=models.CharField(default='udp://127.0.0.1:5002', help_text='For UDP/RTMP: URL (udp://ip:port, rtmp://...). For HLS: directory path.', max_length=512),
        ),
        migrations.AlterField(
            model_name='channel',
            name='audio_codec',
            field=models.CharField(blank=True, default='', help_text='When encoding audio, e.g. aac', max_length=50),
        ),
        migrations.AlterField(
            model_name='channel',
            name='audio_mode',
            field=models.CharField(choices=[('copy', 'Copy (no re-encode)'), ('encode', 'Encode (re-encode)'), ('disable', 'Disable (no audio)')], default='copy', max_length=20),
        ),
        migrations.AlterField(
            model_name='channel',
            name='auto_delete_after_days',
            field=models.PositiveIntegerField(blank=True, help_text='Delete segments older than N days. Leave blank to ignore.', null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='auto_delete_after_segments',
            field=models.PositiveIntegerField(blank=True, help_text='Keep last N segments. Leave blank to ignore.', null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='auto_delete_enabled',
            field=models.BooleanField(default=False, help_text='If enabled, old recording segments will be deleted automatically.'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='date_from',
            field=models.DateField(blank=True, help_text='First active date (inclusive).', null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='date_to',
            field=models.DateField(blank=True, help_text='Last active date (inclusive).', null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='enabled',
            field=models.BooleanField(default=True, help_text='If off, enforcer will not run this channel.'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Local end time. If blank, treated as 00:00. If start == end -> full day.', null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='input_type',
            field=models.CharField(choices=[('udp_multicast', 'UDP Multicast (MPEG-TS)'), ('rtsp', 'RTSP'), ('rtmp', 'RTMP'), ('file', 'File'), ('internal_gen', 'Internal Generator (Test)')], default='udp_multicast', max_length=20),
        ),
        migrations.AlterField(
            model_name='channel',
            name='input_url',
            field=models.CharField(default='udp://@239.0.0.1:5000', help_text='For multicast: e.g. udp://@239.10.10.10:5001 (fifo_size & overrun options may be added automatically). For Internal Generator, this can be internal://generator.', max_length=512),
        ),
        migrations.AlterField(
            model_name='channel',
            name='multicast_interface',
            field=models.CharField(blank=True, default='', help_text='Optional: network interface/IP for multicast receiving (advanced usage).', max_length=64),
        ),
        migrations.AlterField(
            model_name='channel',
            name='playback_tail_enabled',
            field=models.BooleanField(default=False, help_text='If enabled: when schedule ends, recording stops immediately but playback continues until (schedule_end + delay). Useful to flush the delayed buffer.'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Local start time. If blank, treated as 00:00.', null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='video_codec',
            field=models.CharField(blank=True, default='', help_text='When encoding video, e.g. libx264', max_length=50),
        ),
        migrations.AlterField(
            model_name='channel',
            name='video_mode',
            field=models.CharField(choices=[('copy', 'Copy (no re-encode)'), ('encode', 'Encode (re-encode)')], default='copy', max_length=20),
        ),
        migrations.CreateModel(
            name='TimeShiftProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('delay_minutes', models.PositiveIntegerField(default=60, help_text='Delay amount in minutes (0..1440).', validators=[django.core.validators.MaxValueValidator(1440)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timeshift_profile', to='transcoder.channel')),
            ],
            options={
                'verbose_name': 'Time-shift profile',
                'verbose_name_plural': 'Time-shift profiles',
            },
        ),
    ]
