# Generated by Django 6.0 on 2025-12-15 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcoder', '0003_alter_channel_options_remove_channel_delay_seconds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeshiftprofile',
            name='delay_minutes',
        ),
        migrations.AddField(
            model_name='timeshiftprofile',
            name='delay_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Delay in seconds (0..86400). 0 = LIVE mode (no recording, direct restream from input to output). >0 = Time-shift mode (records to disk then plays back with this delay).', validators=[django.core.validators.MaxValueValidator(86400)]),
        ),
    ]
